// Single source of truth for the avatar roster.
// Used by the server (validation, uniqueness) and the client (picker, lists).
// Art lives in /assets/avatars/<id>.svg (generated by `npm run art`).

export const AVATARS = [
  { id: 'lime',     name: 'Lime',          accent: '#7eba2d' },
  { id: 'mandarin', name: 'Mandarin',      accent: '#f8852c' },
  { id: 'blabaer',  name: 'Blåbær',        accent: '#2e7ece' },
  { id: 'leppa',    name: 'Leppa',         accent: '#f48b8f' },
  { id: 'briller',  name: 'Frøken Briller', accent: '#1b838c' },
  { id: 'drue',     name: 'Drue',          accent: '#b170b4' },
  { id: 'sol',      name: 'Sol',           accent: '#fae025' },
  { id: 'sky',      name: 'Sky',           accent: '#88c6db' },
  { id: 'kirsebaer', name: 'Kirsebær',     accent: '#e55666' },
  { id: 'hand',     name: 'Hånda',         accent: '#f0c3c5' },
];

export const AVATAR_IDS = AVATARS.map((a) => a.id);
export const isAvatarId = (id) => AVATAR_IDS.includes(id);
